// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElLoadingDirective: typeof import('element-plus/es')['ElLoadingDirective']
}
export {}
